---
name: streams-app-1

server:
  applicationConnectors:
  - type: http
    port: ${APPLICATION_PORT:-8080}
  adminConnectors:
  - type: http
    port: ${ADMIN_PORT:-8081}

kafka:
  enabled: ${KAFKA_ENABLED:-false}
  bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS:-localhost:9092}

schemaRegistry:
  url: ${SCHEMA_REGISTRY_URL:-http://localhost:8081}