---
server:
  adminConnectors:
  - type: http
    port: ${ADMIN_PORT:-8081}
kafka:
  bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS:-localhost:29092}
zipkin:
  url: ${ZIPKIN_URL:-http://localhost:9411/api/v2/spans}