version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.0
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:5.1.0
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - zookeeper

  producer:
    build: producer-metrics
    environment:
      - HOST=producer
      - JMX_PORT=5555
    depends_on:
      - zookeeper
      - kafka

# https://github.com/cstroe/java-jmx-in-docker-sample-app/blob/master/bin/entrypoint.sh
  consumer:
    build: consumer-metrics
    environment:
      - HOST=consumer
      - JMX_PORT=5555
    depends_on:
      - zookeeper
      - kafka

# https://github:com/rama-nallamilli/kafka-prometheus-monitoring/blob/master/docker-compose:yml
  jmx-exporter-consumer:
    build: jmx-exporter
    volumes:
      - ./jmx-exporter/docker_httpserver_sample_config.yml:/opt/jmx_prometheus_httpserver/httpserver_sample_config.yml
    ports:
      - 8080:8080
    depends_on:
      - consumer

  jmx-exporter-producer:
    build: jmx-exporter
    volumes:
      - ./jmx-exporter/docker_producer_httpserver_sample_config.yml:/opt/jmx_prometheus_httpserver/httpserver_sample_config.yml
    ports:
      - 8081:8080
    depends_on:
      - producer